### ISSUE TITLE
Feature request: Expected VM status 

### ISSUE THREAD

**Issue by holyhope** [NikolaLohinski/terraform-provider-freebox#4]
Hello,

If I am not wrong, the provider keep the VM state as it is.
I would like to be able to specify the state of the machine (`running`/`stopped`) and let the provider start/stop the vm if needed.

This basically means we could make the `status` field writable.

What do you think?

**Comment by NikolaLohinski** [comment]
Hi @holyhope 

Indeed that was the plan all along. It requires a bit more implementation and tests to make sure it bahaves as expected in all cases, but should be pretty straightforward.

Happy to take a PR if you feel like giving it a try. I pretty busy right now with newborns so please don't expect any major adds until for a few months.

Cheers
