### ISSUE TITLE
Feature request: Manage remote file

### ISSUE THREAD

**Issue by holyhope** [NikolaLohinski/terraform-provider-freebox#5]
Hello,

I would like to upload a VM disk built with [Packer](https://www.packer.io/) (but it could be any files).
What do you think about adding a new Terraform resource similar to the [`local_file`](https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file) one.
Since the go sdk currently only support download tasks and not file upload, I suggest to start with something like:

```terraform
resource "freebox_remote_file" "my-disk" {
  source_url = "https://my.domain/the-file"
  checksum = "md5:xxx"
  destination_path = "/path/in/the/freebox"
}
```

What is your opinion on that?

**Comment by NikolaLohinski** [comment]
Hey @holyhope 

Sounds like something useful.

Happy to take PRs in free-go as well. The API is super simple to work with and relatively well documented so feel free to give it a try

Cheers

**Comment by holyhope** [comment]
Hi,

This is nice, let me setup my dev environment and I will (try to) work on that.

Keep in touch.
