### ISSUE TITLE
Bug: Save or clean incomplete resources

### ISSUE THREAD

**Issue by holyhope** [NikolaLohinski/terraform-provider-freebox#7]
Hello,

In my opinion, the provider should either clean the state on failure, or save the state of the VM (my favorite solution).

### Expected behavior

The provider should keep the freebox state in the terraform state.
When it fails to complete the VM creation, it should store the VM ID into the terraform state.

### Current behavior

The provider currently create a VM, but the terraform state remains empty.

#### Steps to reproduce

1. Create a VM with a non-existing disk:

    ```terraform
    resource "freebox_virtual_machine" "server" {
      disk_path = "i-do-not-exist"
      [...]
    }
    ```

2. It fails with an error:
    
    ```
    freebox_virtual_machine.server: Creating...
    ╷
    │ Error: Failed to start virtual machine
    │ 
    │   with freebox_virtual_machine.server,
    │   on deploy.tf line 6, in resource "freebox_virtual_machine" "server":
    │    6: resource "freebox_virtual_machine" "server" {
    │ 
    │ failed to start virtual machine: failed to POST to vm/1/start endpoint: failed with error code 'file_not_found': Impossible de démarrer cette VM : Le fichier de disque n’a pas été trouvé
    ╵
    ```

3. Check on the Freebox UI that a new VM exist.
4. Display the state and see that it is empty

    ```
    $ tf state show freebox_virtual_machine.server
    No instance found for the given address!
    
    This command requires that the address references one specific instance.
    To view the available instances, use "terraform state list". Please modify 
    the address to reference a specific instance.
    ```

**Comment by NikolaLohinski** [comment]
Hey @holyhope 

Looks like a bug indeed. The saving of state should happen before the starting of the VM, which I thought was already the case. But apparently not.

Will have a look and try to fix it.

Cheers
